spring:
  rabbitmq:
    addresses: runtimex.vip:5672
    username: admin
    password: admin
    #开启返回确认
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    virtual-host: /my_vhost
    #开启生产发送重试策略
    template:
      retry:
        enabled: true
        max-attempts: 3
        #最大重试间隔
        max-interval: 10000
        #初始重试间隔
        initial-interval: 1000
    listener:
      simple:
   #     consumer-batch-enabled: true
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 4 #最大重试次数
          initial-interval: 1000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 2 #应用于前一重试间隔的乘法器。
        default-requeue-rejected: false #重试次数超过上面的设置之后是否丢弃


---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://runtimex.vip:3306/seckill?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: zhouhao
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    host: runtimex.vip
    password: zhouhao
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 20000
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 20000


## 该配置节点为独立的节点，将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.rabbit.seckill.model  # 注意：对应实体类的路径
app:
  jpush-message:
    #    app-key: 7f46241be02eb0e589a1e84b
    #    master-secret: f4d60bebe3d7b556798dc996
    app-key: 859e02a2c3be8edc65004ce0
    master-secret: 63581e35186268e7a4853d82
    apns-production: false
    push-url: https://api.jpush.cn/v3/push #向某单个设备或者某设备列表推送一条通知、或者消息。POST
logging:
  level:
    com.rabbit.shop.mapper: debug
