server:
  port: 8080
  servlet:
    context-path: /wx
spring:
  application:
    name: wx

app:
  wx:
    app-id: wxc6ebce156858e2
    app-secret: fb185de90a198241d1191d231
    pay:
      appId: wxc6ebce156858
      mchId: 16105329 # 商户号
      mchKey: bjs7sSa0kMJwUYhsSQsF87mNi #秘钥
      apiv3Key: bjs7sSa0kMJwUYhsSQs7K3i
      certSerialNo: 7D232FA57F969FE7EE97B5F11027
      #subAppId: #子商户号
      #subMchId: #子商户号
      keyPath: classpath:/pay/wx/apiclien12
      privateKeyPath: classpath:/pay/wx/key.pem
      privateCertPath: classpath:/pay/wx/apiccert.pem


