server:
  port: 8080
  servlet:
    context-path: /wx
spring:
  application:
    name: wx

app:
  wx:
    app-id: wxc6ebce156858e28f
    app-secret: fb185de90a198241d1191d23187e84e0
    pay:
      appId: wxc6ebce156858e28f
      mchId: 1610532911 # 商户号
      mchKey: bjs7sSa0kMJwUYhsSQsF87mNsnvh7K3i #秘钥
      apiv3Key: bjs7sSa0kMJwUYhsSQsF87mNsnvh7K3i
      certSerialNo: 7D232FA57F969FE325B952975DA7EE97B5F11027
      #subAppId: #子商户号
      #subMchId: #子商户号
      keyPath: classpath:/pay/wx/apiclient_cert.p12
      privateKeyPath: classpath:/pay/wx/apiclient_key.pem
      privateCertPath: classpath:/pay/wx/apiclient_cert.pem


