spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://runtimex.vip:3306/order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zhouhao
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: runtimex.vip
    password: zhouhao
    database: 1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
app:
  redis:
    enabled: true
  cache:
    mode: redis
  shiro:
    enabled: true
    filter-chain-definition-map:
      "[/app/doLogin]": anon
      "[/app/logout]": jwt
      "[/app/**]": jwt
      #如果没有登录进行身份认证，authc的url会跳转到登录的url,authc只会在登录的时候执行认证，登录完了，后面再执行其他接口就不会走认证流程
      #如果使用了权限注解，没有通过身份认证的会直接抛出认证失败的异常
      "[/user/**]": jwt

